### ISSUE TITLE
Unfriendly use as a library/package

### ISSUE THREAD

**Issue by Myriad-Dreamin** [QuarticCat/detypify#4]
We need an extra step to download detypify assets. What's worse is that we should keep in mind and update the assets on detypify upgrade its pre-trained model.

https://github.com/Myriad-Dreamin/tinymist/issues/260

Possible solution: publish and install it via npm: `yarn add detypify`
```ts
import {Detypify} from 'detypify';
console.log((await Detypify.create()).candidates(strokes));
```

https://github.com/Myriad-Dreamin/tinymist/blob/01f72c3d75b099afff7ff59c394067e57b79027a/tools/editor-tools/src/features/symbol-view.detypify.ts

**Comment by QuarticCat** [comment]
Close as fixed in 0.2.4
